<section class="b-dark">
	<div class="outer-container">
		<footer class="panel panel-text">
			<ul>
				<li>&copy;<?php echo date('Y'); ?> <a href="http://ifas.ufl.edu/">Institute of Food and Agricultural Sciences</a> and <a href="http://ufl.edu">University of Florida</a></li>
				<li>P.O. Box 110180 | Gainesville, FL 32611-0180 | Phone: (352) 392-1971</li>
				<li>This page uses Google Analytics (<a href="http://www.google.com/policies/privacy/">Google Privacy Policy</a>)</li>
				<li>Policies: <a href="http://privacy.ufl.edu/privacystatement.html">UF Privacy</a> | <a href="http://privacy.ufl.edu/SSNPrivacy.html">SSN Privacy</a> | <a href="http://ics.ifas.ufl.edu/social-media.shtml">Social Media</a> | <a href="http://ics.ifas.ufl.edu/web.shtml">IFAS Web Policy</a> | <a href="/style-guide-secondary.shtml">Style Guide</a></li>
				<li id="last-mod"><a href="mailto:webteam@ifas.ufl.edu?subject=IFAS Refresh Feedback">Contact Webteam</a> | Last Modified:
					<!-- #BeginDate format:Am1 -->January 7, 2015<!-- #EndDate -->
				</li>
			</ul>
			<img src="templates/img/UF_Signature.svg" alt="">
		</footer>
	</div>
</section>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="templates/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
<script src="templates/js/vendor/responsiveslides.min.js"></script>
<script src="templates/js/main.js"></script>
</body>
</html>